import { db } from '@/db';
import { documents } from '@/db/schema';

async function main() {
    const sampleDocuments = [
        // Health Reports (8 documents - no expiry dates, all active)
        {
            screeningId: 1,
            fileName: 'saglik_raporu_2024_07_15.pdf',
            fileUrl: '/uploads/documents/saglik_raporu_2024_07_15.pdf',
            fileSize: 2458624,
            fileType: 'application/pdf',
            uploadedAt: new Date('2024-07-15T09:30:00').toISOString(),
            notes: 'Toplu işe giriş muayene raporu',
            title: 'Toplu İşe Giriş Muayene Raporu - Temmuz 2024',
            description: 'ABC Tekstil çalışanları için yapılan toplu işe giriş muayenesi sonuç raporu',
            category: 'health_report',
            companyId: 1,
            employeeId: 1,
            expiryDate: null,
            uploadDate: new Date('2024-07-15T09:30:00').toISOString(),
            uploadedBy: 'Dr. Mehmet Yılmaz',
            status: 'active',
            createdAt: new Date('2024-07-15T09:30:00').toISOString(),
            updatedAt: new Date('2024-07-15T09:30:00').toISOString(),
        },
        {
            screeningId: 2,
            fileName: 'periyodik_muayene_raporu_2024_08_20.pdf',
            fileUrl: '/uploads/documents/periyodik_muayene_raporu_2024_08_20.pdf',
            fileSize: 1876543,
            fileType: 'application/pdf',
            uploadedAt: new Date('2024-08-20T14:15:00').toISOString(),
            notes: 'Yıllık periyodik muayene sonuçları',
            title: 'Periyodik Sağlık Muayenesi Raporu - Ağustos 2024',
            description: 'XYZ İnşaat çalışanları için yapılan yıllık periyodik sağlık muayenesi sonuçları',
            category: 'health_report',
            companyId: 2,
            employeeId: 2,
            expiryDate: null,
            uploadDate: new Date('2024-08-20T14:15:00').toISOString(),
            uploadedBy: 'Dr. Ayşe Demir',
            status: 'active',
            createdAt: new Date('2024-08-20T14:15:00').toISOString(),
            updatedAt: new Date('2024-08-20T14:15:00').toISOString(),
        },
        {
            screeningId: 3,
            fileName: 'laboratuvar_sonuclari_2024_09_10.pdf',
            fileUrl: '/uploads/documents/laboratuvar_sonuclari_2024_09_10.pdf',
            fileSize: 3125789,
            fileType: 'application/pdf',
            uploadedAt: new Date('2024-09-10T11:00:00').toISOString(),
            notes: 'Kan tahlili ve idrar tetkiki sonuçları',
            title: 'Laboratuvar Test Sonuçları - Eylül 2024',
            description: 'TechCorp Yazılım çalışanları için yapılan laboratuvar testleri sonuçları',
            category: 'health_report',
            companyId: 3,
            employeeId: 3,
            expiryDate: null,
            uploadDate: new Date('2024-09-10T11:00:00').toISOString(),
            uploadedBy: 'Hemşire Fatma Kaya',
            status: 'active',
            createdAt: new Date('2024-09-10T11:00:00').toISOString(),
            updatedAt: new Date('2024-09-10T11:00:00').toISOString(),
        },
        {
            screeningId: 4,
            fileName: 'gorusme_formu_2024_10_05.pdf',
            fileUrl: '/uploads/documents/gorusme_formu_2024_10_05.pdf',
            fileSize: 1456320,
            fileType: 'application/pdf',
            uploadedAt: new Date('2024-10-05T10:30:00').toISOString(),
            notes: 'İş sağlığı ve güvenliği görüşme formu',
            title: 'İSG Görüşme Formu - Ekim 2024',
            description: 'ABC Tekstil için iş sağlığı ve güvenliği görüşme kayıtları',
            category: 'health_report',
            companyId: 1,
            employeeId: 4,
            expiryDate: null,
            uploadDate: new Date('2024-10-05T10:30:00').toISOString(),
            uploadedBy: 'Dr. Mehmet Yılmaz',
            status: 'active',
            createdAt: new Date('2024-10-05T10:30:00').toISOString(),
            updatedAt: new Date('2024-10-05T10:30:00').toISOString(),
        },
        {
            screeningId: 5,
            fileName: 'risk_degerlendirme_raporu_2024_11_12.pdf',
            fileUrl: '/uploads/documents/risk_degerlendirme_raporu_2024_11_12.pdf',
            fileSize: 2789456,
            fileType: 'application/pdf',
            uploadedAt: new Date('2024-11-12T15:45:00').toISOString(),
            notes: 'İşyeri risk değerlendirmesi sonuçları',
            title: 'İşyeri Risk Değerlendirme Raporu - Kasım 2024',
            description: 'XYZ İnşaat şantiyesi için yapılan risk değerlendirmesi',
            category: 'health_report',
            companyId: 2,
            employeeId: 5,
            expiryDate: null,
            uploadDate: new Date('2024-11-12T15:45:00').toISOString(),
            uploadedBy: 'İSG Uzmanı Ali Veli',
            status: 'active',
            createdAt: new Date('2024-11-12T15:45:00').toISOString(),
            updatedAt: new Date('2024-11-12T15:45:00').toISOString(),
        },
        {
            screeningId: null,
            fileName: 'meslek_hastaliklari_tarama_2024_12_08.pdf',
            fileUrl: '/uploads/documents/meslek_hastaliklari_tarama_2024_12_08.pdf',
            fileSize: 2156789,
            fileType: 'application/pdf',
            uploadedAt: new Date('2024-12-08T09:00:00').toISOString(),
            notes: 'Meslek hastalıkları tarama sonuçları',
            title: 'Meslek Hastalıkları Tarama Raporu - Aralık 2024',
            description: 'TechCorp Yazılım için yapılan meslek hastalıkları taraması',
            category: 'health_report',
            companyId: 3,
            employeeId: 6,
            expiryDate: null,
            uploadDate: new Date('2024-12-08T09:00:00').toISOString(),
            uploadedBy: 'Dr. Zeynep Şahin',
            status: 'active',
            createdAt: new Date('2024-12-08T09:00:00').toISOString(),
            updatedAt: new Date('2024-12-08T09:00:00').toISOString(),
        },
        {
            screeningId: null,
            fileName: 'asi_kayitlari_2025_01_10.pdf',
            fileUrl: '/uploads/documents/asi_kayitlari_2025_01_10.pdf',
            fileSize: 1678900,
            fileType: 'application/pdf',
            uploadedAt: new Date('2025-01-10T13:20:00').toISOString(),
            notes: 'Çalışan aşılama kayıtları',
            title: 'Çalışan Aşı Kayıtları - Ocak 2025',
            description: 'ABC Tekstil çalışanları için yapılan aşılama kayıtları',
            category: 'health_report',
            companyId: 1,
            employeeId: 1,
            expiryDate: null,
            uploadDate: new Date('2025-01-10T13:20:00').toISOString(),
            uploadedBy: 'Hemşire Fatma Kaya',
            status: 'active',
            createdAt: new Date('2025-01-10T13:20:00').toISOString(),
            updatedAt: new Date('2025-01-10T13:20:00').toISOString(),
        },
        {
            screeningId: null,
            fileName: 'saglik_egitimi_kayitlari_2025_01_20.pdf',
            fileUrl: '/uploads/documents/saglik_egitimi_kayitlari_2025_01_20.pdf',
            fileSize: 1234567,
            fileType: 'application/pdf',
            uploadedAt: new Date('2025-01-20T10:15:00').toISOString(),
            notes: 'İş sağlığı eğitim kayıtları',
            title: 'İş Sağlığı Eğitim Kayıtları - Ocak 2025',
            description: 'XYZ İnşaat çalışanları için verilen iş sağlığı eğitimleri',
            category: 'health_report',
            companyId: 2,
            employeeId: 2,
            expiryDate: null,
            uploadDate: new Date('2025-01-20T10:15:00').toISOString(),
            uploadedBy: 'İSG Uzmanı Ali Veli',
            status: 'active',
            createdAt: new Date('2025-01-20T10:15:00').toISOString(),
            updatedAt: new Date('2025-01-20T10:15:00').toISOString(),
        },

        // Certificates (8 documents - ALL with expiry dates, mixed statuses)
        {
            screeningId: null,
            fileName: 'isg_uzmani_sertifikasi_2023.pdf',
            fileUrl: '/uploads/documents/isg_uzmani_sertifikasi_2023.pdf',
            fileSize: 1567890,
            fileType: 'application/pdf',
            uploadedAt: new Date('2024-07-20T11:00:00').toISOString(),
            notes: 'A Sınıfı İSG Uzmanı sertifikası - süresi doldu',
            title: 'A Sınıfı İSG Uzmanı Sertifikası',
            description: 'Çalışma ve Sosyal Güvenlik Bakanlığı onaylı İSG Uzmanı sertifikası',
            category: 'certificate',
            companyId: null,
            employeeId: 1,
            expiryDate: '2024-12-31',
            uploadDate: new Date('2024-07-20T11:00:00').toISOString(),
            uploadedBy: 'Dr. Mehmet Yılmaz',
            status: 'expired',
            createdAt: new Date('2024-07-20T11:00:00').toISOString(),
            updatedAt: new Date('2025-01-15T09:00:00').toISOString(),
        },
        {
            screeningId: null,
            fileName: 'isyeri_hekimligi_sertifikasi_2024.pdf',
            fileUrl: '/uploads/documents/isyeri_hekimligi_sertifikasi_2024.pdf',
            fileSize: 1789012,
            fileType: 'application/pdf',
            uploadedAt: new Date('2024-08-15T14:30:00').toISOString(),
            notes: 'İşyeri Hekimliği Sertifikası - yakında yenilenecek',
            title: 'İşyeri Hekimliği Sertifikası',
            description: 'İşyeri Hekimliği yetki belgesi - Sağlık Bakanlığı onaylı',
            category: 'certificate',
            companyId: null,
            employeeId: 2,
            expiryDate: '2025-02-15',
            uploadDate: new Date('2024-08-15T14:30:00').toISOString(),
            uploadedBy: 'Dr. Ayşe Demir',
            status: 'active',
            createdAt: new Date('2024-08-15T14:30:00').toISOString(),
            updatedAt: new Date('2024-08-15T14:30:00').toISOString(),
        },
        {
            screeningId: null,
            fileName: 'ilk_yardim_sertifikasi_2024.pdf',
            fileUrl: '/uploads/documents/ilk_yardim_sertifikasi_2024.pdf',
            fileSize: 987654,
            fileType: 'application/pdf',
            uploadedAt: new Date('2024-09-05T10:00:00').toISOString(),
            notes: 'İlk Yardım Eğitimi Sertifikası - süresi doldu',
            title: 'İlk Yardım Eğitimi Sertifikası',
            description: 'Kızılay onaylı İlk Yardım Eğitimi tamamlama sertifikası',
            category: 'certificate',
            companyId: null,
            employeeId: 3,
            expiryDate: '2025-01-15',
            uploadDate: new Date('2024-09-05T10:00:00').toISOString(),
            uploadedBy: 'Hemşire Fatma Kaya',
            status: 'expired',
            createdAt: new Date('2024-09-05T10:00:00').toISOString(),
            updatedAt: new Date('2025-01-20T11:00:00').toISOString(),
        },
        {
            screeningId: null,
            fileName: 'yangina_mudahale_sertifikasi_2024.pdf',
            fileUrl: '/uploads/documents/yangina_mudahale_sertifikasi_2024.pdf',
            fileSize: 1345678,
            fileType: 'application/pdf',
            uploadedAt: new Date('2024-10-12T09:15:00').toISOString(),
            notes: 'Yangına Müdahale Eğitimi Sertifikası',
            title: 'Yangına Müdahale ve Söndürme Eğitimi Sertifikası',
            description: 'İtfaiye Dairesi onaylı Yangına Müdahale Eğitimi sertifikası',
            category: 'certificate',
            companyId: null,
            employeeId: 4,
            expiryDate: '2026-10-12',
            uploadDate: new Date('2024-10-12T09:15:00').toISOString(),
            uploadedBy: 'İSG Uzmanı Ali Veli',
            status: 'active',
            createdAt: new Date('2024-10-12T09:15:00').toISOString(),
            updatedAt: new Date('2024-10-12T09:15:00').toISOString(),
        },
        {
            screeningId: null,
            fileName: 'acil_durum_egitimi_sertifikasi_2023.pdf',
            fileUrl: '/uploads/documents/acil_durum_egitimi_sertifikasi_2023.pdf',
            fileSize: 1123456,
            fileType: 'application/pdf',
            uploadedAt: new Date('2024-11-08T13:45:00').toISOString(),
            notes: 'Acil Durum Yönetimi Sertifikası - süresi doldu',
            title: 'Acil Durum Yönetimi Eğitimi Sertifikası',
            description: 'AFAD onaylı Acil Durum Yönetimi eğitimi sertifikası',
            category: 'certificate',
            companyId: null,
            employeeId: 5,
            expiryDate: '2025-01-10',
            uploadDate: new Date('2024-11-08T13:45:00').toISOString(),
            uploadedBy: 'Dr. Zeynep Şahin',
            status: 'expired',
            createdAt: new Date('2024-11-08T13:45:00').toISOString(),
            updatedAt: new Date('2025-01-18T10:00:00').toISOString(),
        },
        {
            screeningId: null,
            fileName: 'isg_egitimi_sertifikasi_2024.pdf',
            fileUrl: '/uploads/documents/isg_egitimi_sertifikasi_2024.pdf',
            fileSize: 1456789,
            fileType: 'application/pdf',
            uploadedAt: new Date('2024-12-15T11:30:00').toISOString(),
            notes: 'İSG Temel Eğitimi Sertifikası - yakında yenilenecek',
            title: 'İSG Temel Eğitimi Sertifikası',
            description: 'Çalışma Bakanlığı onaylı İSG Temel Eğitimi sertifikası',
            category: 'certificate',
            companyId: null,
            employeeId: 6,
            expiryDate: '2025-02-20',
            uploadDate: new Date('2024-12-15T11:30:00').toISOString(),
            uploadedBy: 'İSG Uzmanı Ali Veli',
            status: 'active',
            createdAt: new Date('2024-12-15T11:30:00').toISOString(),
            updatedAt: new Date('2024-12-15T11:30:00').toISOString(),
        },
        {
            screeningId: null,
            fileName: 'yuksekte_calisma_sertifikasi_2023.pdf',
            fileUrl: '/uploads/documents/yuksekte_calisma_sertifikasi_2023.pdf',
            fileSize: 1234567,
            fileType: 'application/pdf',
            uploadedAt: new Date('2025-01-05T10:00:00').toISOString(),
            notes: 'Yüksekte Çalışma Eğitimi Sertifikası - süresi doldu',
            title: 'Yüksekte Güvenli Çalışma Eğitimi Sertifikası',
            description: 'İSG kurumu onaylı Yüksekte Çalışma eğitimi sertifikası',
            category: 'certificate',
            companyId: null,
            employeeId: 1,
            expiryDate: '2025-01-20',
            uploadDate: new Date('2025-01-05T10:00:00').toISOString(),
            uploadedBy: 'Dr. Mehmet Yılmaz',
            status: 'expired',
            createdAt: new Date('2025-01-05T10:00:00').toISOString(),
            updatedAt: new Date('2025-01-25T09:00:00').toISOString(),
        },
        {
            screeningId: null,
            fileName: 'kimyasal_madde_guvenligi_sertifikasi_2024.pdf',
            fileUrl: '/uploads/documents/kimyasal_madde_guvenligi_sertifikasi_2024.pdf',
            fileSize: 1567890,
            fileType: 'application/pdf',
            uploadedAt: new Date('2025-01-15T14:20:00').toISOString(),
            notes: 'Kimyasal Madde Güvenliği Sertifikası - yakında yenilenecek',
            title: 'Kimyasal Madde Güvenliği Eğitimi Sertifikası',
            description: 'Çevre ve Şehircilik Bakanlığı onaylı kimyasal güvenlik sertifikası',
            category: 'certificate',
            companyId: null,
            employeeId: 2,
            expiryDate: '2025-02-10',
            uploadDate: new Date('2025-01-15T14:20:00').toISOString(),
            uploadedBy: 'Dr. Ayşe Demir',
            status: 'active',
            createdAt: new Date('2025-01-15T14:20:00').toISOString(),
            updatedAt: new Date('2025-01-15T14:20:00').toISOString(),
        },

        // Contracts (6 documents - some with expiry dates)
        {
            screeningId: null,
            fileName: 'osgb_hizmet_sozlesmesi_abc_tekstil_2024.pdf',
            fileUrl: '/uploads/documents/osgb_hizmet_sozlesmesi_abc_tekstil_2024.pdf',
            fileSize: 3456789,
            fileType: 'application/pdf',
            uploadedAt: new Date('2024-07-25T09:00:00').toISOString(),
            notes: 'ABC Tekstil OSGB hizmet sözleşmesi - süresi doldu',
            title: 'OSGB Hizmet Sözleşmesi - ABC Tekstil',
            description: 'ABC Tekstil ile yapılan Ortak Sağlık Güvenlik Birimi hizmet sözleşmesi',
            category: 'contract',
            companyId: 1,
            employeeId: null,
            expiryDate: '2025-01-01',
            uploadDate: new Date('2024-07-25T09:00:00').toISOString(),
            uploadedBy: 'Yönetici Ahmet Kaya',
            status: 'expired',
            createdAt: new Date('2024-07-25T09:00:00').toISOString(),
            updatedAt: new Date('2025-01-10T10:00:00').toISOString(),
        },
        {
            screeningId: null,
            fileName: 'isyeri_hekimligi_sozlesmesi_xyz_insaat_2024.pdf',
            fileUrl: '/uploads/documents/isyeri_hekimligi_sozlesmesi_xyz_insaat_2024.pdf',
            fileSize: 2789012,
            fileType: 'application/pdf',
            uploadedAt: new Date('2024-08-30T11:15:00').toISOString(),
            notes: 'XYZ İnşaat işyeri hekimliği hizmet sözleşmesi',
            title: 'İşyeri Hekimliği Hizmet Sözleşmesi - XYZ İnşaat',
            description: 'XYZ İnşaat için işyeri hekimliği hizmet sözleşmesi',
            category: 'contract',
            companyId: 2,
            employeeId: null,
            expiryDate: '2026-08-30',
            uploadDate: new Date('2024-08-30T11:15:00').toISOString(),
            uploadedBy: 'Yönetici Ahmet Kaya',
            status: 'active',
            createdAt: new Date('2024-08-30T11:15:00').toISOString(),
            updatedAt: new Date('2024-08-30T11:15:00').toISOString(),
        },
        {
            screeningId: null,
            fileName: 'periyodik_muayene_sozlesmesi_techcorp_2024.pdf',
            fileUrl: '/uploads/documents/periyodik_muayene_sozlesmesi_techcorp_2024.pdf',
            fileSize: 2345678,
            fileType: 'application/pdf',
            uploadedAt: new Date('2024-09-20T13:30:00').toISOString(),
            notes: 'TechCorp periyodik muayene hizmet sözleşmesi',
            title: 'Periyodik Muayene Hizmet Sözleşmesi - TechCorp',
            description: 'TechCorp Yazılım için yıllık periyodik muayene hizmet sözleşmesi',
            category: 'contract',
            companyId: 3,
            employeeId: null,
            expiryDate: null,
            uploadDate: new Date('2024-09-20T13:30:00').toISOString(),
            uploadedBy: 'Yönetici Ahmet Kaya',
            status: 'active',
            createdAt: new Date('2024-09-20T13:30:00').toISOString(),
            updatedAt: new Date('2024-09-20T13:30:00').toISOString(),
        },
        {
            screeningId: null,
            fileName: 'danismanlik_sozlesmesi_abc_tekstil_2024.pdf',
            fileUrl: '/uploads/documents/danismanlik_sozlesmesi_abc_tekstil_2024.pdf',
            fileSize: 1987654,
            fileType: 'application/pdf',
            uploadedAt: new Date('2024-10-25T10:45:00').toISOString(),
            notes: 'İSG danışmanlık hizmet sözleşmesi',
            title: 'İSG Danışmanlık Hizmet Sözleşmesi - ABC Tekstil',
            description: 'ABC Tekstil için İş Sağlığı ve Güvenliği danışmanlık sözleşmesi',
            category: 'contract',
            companyId: 1,
            employeeId: null,
            expiryDate: '2025-10-25',
            uploadDate: new Date('2024-10-25T10:45:00').toISOString(),
            uploadedBy: 'Yönetici Ahmet Kaya',
            status: 'active',
            createdAt: new Date('2024-10-25T10:45:00').toISOString(),
            updatedAt: new Date('2024-10-25T10:45:00').toISOString(),
        },
        {
            screeningId: null,
            fileName: 'egitim_hizmeti_sozlesmesi_xyz_insaat_2024.pdf',
            fileUrl: '/uploads/documents/egitim_hizmeti_sozlesmesi_xyz_insaat_2024.pdf',
            fileSize: 2123456,
            fileType: 'application/pdf',
            uploadedAt: new Date('2024-11-30T14:00:00').toISOString(),
            notes: 'İSG eğitim hizmeti sözleşmesi - arşivlendi',
            title: 'İSG Eğitim Hizmeti Sözleşmesi - XYZ İnşaat',
            description: 'XYZ İnşaat çalışanları için İSG eğitim hizmeti sözleşmesi',
            category: 'contract',
            companyId: 2,
            employeeId: null,
            expiryDate: null,
            uploadDate: new Date('2024-11-30T14:00:00').toISOString(),
            uploadedBy: 'Yönetici Ahmet Kaya',
            status: 'archived',
            createdAt: new Date('2024-11-30T14:00:00').toISOString(),
            updatedAt: new Date('2025-01-15T09:00:00').toISOString(),
        },
        {
            screeningId: null,
            fileName: 'laboratuvar_hizmeti_sozlesmesi_techcorp_2025.pdf',
            fileUrl: '/uploads/documents/laboratuvar_hizmeti_sozlesmesi_techcorp_2025.pdf',
            fileSize: 1876543,
            fileType: 'application/pdf',
            uploadedAt: new Date('2025-01-10T09:30:00').toISOString(),
            notes: 'Laboratuvar test hizmetleri sözleşmesi',
            title: 'Laboratuvar Test Hizmeti Sözleşmesi - TechCorp',
            description: 'TechCorp Yazılım için laboratuvar test hizmetleri sözleşmesi',
            category: 'contract',
            companyId: 3,
            employeeId: null,
            expiryDate: '2026-01-10',
            uploadDate: new Date('2025-01-10T09:30:00').toISOString(),
            uploadedBy: 'Yönetici Ahmet Kaya',
            status: 'active',
            createdAt: new Date('2025-01-10T09:30:00').toISOString(),
            updatedAt: new Date('2025-01-10T09:30:00').toISOString(),
        },

        // Identification (5 documents - no expiry dates)
        {
            screeningId: null,
            fileName: 'isyeri_sicil_belgesi_abc_tekstil.pdf',
            fileUrl: '/uploads/documents/isyeri_sicil_belgesi_abc_tekstil.pdf',
            fileSize: 1567890,
            fileType: 'application/pdf',
            uploadedAt: new Date('2024-08-05T10:00:00').toISOString(),
            notes: 'İşyeri sicil belgesi',
            title: 'İşyeri Sicil Belgesi - ABC Tekstil',
            description: 'ABC Tekstil işyeri sicil belgesi - SGK kaydı',
            category: 'identification',
            companyId: 1,
            employeeId: null,
            expiryDate: null,
            uploadDate: new Date('2024-08-05T10:00:00').toISOString(),
            uploadedBy: 'İK Müdürü Elif Yıldız',
            status: 'active',
            createdAt: new Date('2024-08-05T10:00:00').toISOString(),
            updatedAt: new Date('2024-08-05T10:00:00').toISOString(),
        },
        {
            screeningId: null,
            fileName: 'vergi_levhasi_xyz_insaat.pdf',
            fileUrl: '/uploads/documents/vergi_levhasi_xyz_insaat.pdf',
            fileSize: 987654,
            fileType: 'application/pdf',
            uploadedAt: new Date('2024-09-15T11:30:00').toISOString(),
            notes: 'Vergi levhası',
            title: 'Vergi Levhası - XYZ İnşaat',
            description: 'XYZ İnşaat vergi levhası belgesi',
            category: 'identification',
            companyId: 2,
            employeeId: null,
            expiryDate: null,
            uploadDate: new Date('2024-09-15T11:30:00').toISOString(),
            uploadedBy: 'Mali İşler Sorumlusu Mehmet Aslan',
            status: 'active',
            createdAt: new Date('2024-09-15T11:30:00').toISOString(),
            updatedAt: new Date('2024-09-15T11:30:00').toISOString(),
        },
        {
            screeningId: null,
            fileName: 'ticaret_sicil_gazetesi_techcorp.pdf',
            fileUrl: '/uploads/documents/ticaret_sicil_gazetesi_techcorp.pdf',
            fileSize: 2345678,
            fileType: 'application/pdf',
            uploadedAt: new Date('2024-10-20T09:00:00').toISOString(),
            notes: 'Ticaret sicil gazetesi',
            title: 'Ticaret Sicil Gazetesi - TechCorp',
            description: 'TechCorp Yazılım ticaret sicil gazetesi',
            category: 'identification',
            companyId: 3,
            employeeId: null,
            expiryDate: null,
            uploadDate: new Date('2024-10-20T09:00:00').toISOString(),
            uploadedBy: 'Hukuk Müşaviri Ayşe Korkmaz',
            status: 'active',
            createdAt: new Date('2024-10-20T09:00:00').toISOString(),
            updatedAt: new Date('2024-10-20T09:00:00').toISOString(),
        },
        {
            screeningId: null,
            fileName: 'imza_sirkusu_abc_tekstil.pdf',
            fileUrl: '/uploads/documents/imza_sirkusu_abc_tekstil.pdf',
            fileSize: 1234567,
            fileType: 'application/pdf',
            uploadedAt: new Date('2024-11-25T13:15:00').toISOString(),
            notes: 'Şirket imza sirküsü',
            title: 'İmza Sirküsü - ABC Tekstil',
            description: 'ABC Tekstil şirket imza sirküsü belgesi',
            category: 'identification',
            companyId: 1,
            employeeId: null,
            expiryDate: null,
            uploadDate: new Date('2024-11-25T13:15:00').toISOString(),
            uploadedBy: 'Genel Müdür Yardımcısı Can Özdemir',
            status: 'active',
            createdAt: new Date('2024-11-25T13:15:00').toISOString(),
            updatedAt: new Date('2024-11-25T13:15:00').toISOString(),
        },
        {
            screeningId: null,
            fileName: 'faaliyet_belgesi_xyz_insaat.pdf',
            fileUrl: '/uploads/documents/faaliyet_belgesi_xyz_insaat.pdf',
            fileSize: 1456789,
            fileType: 'application/pdf',
            uploadedAt: new Date('2025-01-05T10:30:00').toISOString(),
            notes: 'İnşaat faaliyet belgesi',
            title: 'İnşaat Faaliyet Belgesi - XYZ İnşaat',
            description: 'XYZ İnşaat inşaat faaliyet belgesi',
            category: 'identification',
            companyId: 2,
            employeeId: null,
            expiryDate: null,
            uploadDate: new Date('2025-01-05T10:30:00').toISOString(),
            uploadedBy: 'Proje Müdürü Kemal Yıldırım',
            status: 'active',
            createdAt: new Date('2025-01-05T10:30:00').toISOString(),
            updatedAt: new Date('2025-01-05T10:30:00').toISOString(),
        },

        // Other (3 documents - no expiry dates)
        {
            screeningId: null,
            fileName: 'acil_durum_plani_abc_tekstil_2024.pdf',
            fileUrl: '/uploads/documents/acil_durum_plani_abc_tekstil_2024.pdf',
            fileSize: 3456789,
            fileType: 'application/pdf',
            uploadedAt: new Date('2024-09-30T14:00:00').toISOString(),
            notes: 'İşyeri acil durum eylem planı',
            title: 'Acil Durum Eylem Planı - ABC Tekstil',
            description: 'ABC Tekstil için hazırlanan acil durum ve tahliye planı',
            category: 'other',
            companyId: 1,
            employeeId: null,
            expiryDate: null,
            uploadDate: new Date('2024-09-30T14:00:00').toISOString(),
            uploadedBy: 'İSG Uzmanı Ali Veli',
            status: 'active',
            createdAt: new Date('2024-09-30T14:00:00').toISOString(),
            updatedAt: new Date('2024-09-30T14:00:00').toISOString(),
        },
        {
            screeningId: null,
            fileName: 'calisan_el_kitabi_techcorp_2024.pdf',
            fileUrl: '/uploads/documents/calisan_el_kitabi_techcorp_2024.pdf',
            fileSize: 2789012,
            fileType: 'application/pdf',
            uploadedAt: new Date('2024-12-05T11:00:00').toISOString(),
            notes: 'Çalışan el kitabı ve İSG prosedürleri - arşivlendi',
            title: 'Çalışan El Kitabı ve İSG Prosedürleri - TechCorp',
            description: 'TechCorp Yazılım çalışan el kitabı ve iş sağlığı güvenliği prosedürleri',
            category: 'other',
            companyId: 3,
            employeeId: null,
            expiryDate: null,
            uploadDate: new Date('2024-12-05T11:00:00').toISOString(),
            uploadedBy: 'İK Müdürü Elif Yıldız',
            status: 'archived',
            createdAt: new Date('2024-12-05T11:00:00').toISOString(),
            updatedAt: new Date('2025-01-10T09:00:00').toISOString(),
        },
        {
            screeningId: null,
            fileName: 'kisisel_koruyucu_ekipman_listesi_xyz_insaat_2025.pdf',
            fileUrl: '/uploads/documents/kisisel_koruyucu_ekipman_listesi_xyz_insaat_2025.pdf',
            fileSize: 1567890,
            fileType: 'application/pdf',
            uploadedAt: new Date('2025-01-15T10:00:00').toISOString(),
            notes: 'Kişisel koruyucu ekipman listesi ve kullanım talimatları',
            title: 'Kişisel Koruyucu Ekipman Listesi - XYZ İnşaat',
            description: 'XYZ İnşaat şantiyesi için gerekli KKE listesi ve kullanım talimatları',
            category: 'other',
            companyId: 2,
            employeeId: null,
            expiryDate: null,
            uploadDate: new Date('2025-01-15T10:00:00').toISOString(),
            uploadedBy: 'Şantiye Şefi Mustafa Aydın',
            status: 'active',
            createdAt: new Date('2025-01-15T10:00:00').toISOString(),
            updatedAt: new Date('2025-01-15T10:00:00').toISOString(),
        },
    ];

    await db.insert(documents).values(sampleDocuments);
    
    console.log('✅ Documents seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});