import { db } from '@/db';
import { quotes, quoteItems } from '@/db/schema';

async function main() {
    // Sample quotes data with realistic Turkish OSGB scenarios
    const sampleQuotes = [
        {
            companyId: 1,
            quoteNumber: 'QT-20241015-001',
            issueDate: new Date('2024-10-15').toISOString(),
            validUntilDate: new Date('2024-11-14').toISOString(),
            subtotal: 2280.0,
            tax: 410.4,
            total: 2690.4,
            notes: 'İşe giriş sağlık muayenesi paketi - 20 çalışan için hazırlanmıştır. Tüm tetkikler firmamız sağlık merkezinde yapılacaktır.',
            status: 'draft',
            createdAt: new Date('2024-10-15').toISOString(),
            updatedAt: new Date('2024-10-15').toISOString(),
        },
        {
            companyId: 2,
            quoteNumber: 'QT-20241020-002',
            issueDate: new Date('2024-10-20').toISOString(),
            validUntilDate: new Date('2024-11-19').toISOString(),
            subtotal: 1650.0,
            tax: 297.0,
            total: 1947.0,
            notes: 'Periyodik sağlık muayenesi - Ofis çalışanları için temel tarama paketi.',
            status: 'draft',
            createdAt: new Date('2024-10-20').toISOString(),
            updatedAt: new Date('2024-10-20').toISOString(),
        },
        {
            companyId: 3,
            quoteNumber: 'QT-20241025-003',
            issueDate: new Date('2024-10-25').toISOString(),
            validUntilDate: new Date('2024-11-24').toISOString(),
            subtotal: 3400.0,
            tax: 612.0,
            total: 4012.0,
            notes: 'Gürültülü ortamda çalışan personel için özel muayene paketi. Odyometri testleri dahildir.',
            status: 'draft',
            createdAt: new Date('2024-10-25').toISOString(),
            updatedAt: new Date('2024-10-25').toISOString(),
        },
        {
            companyId: 1,
            quoteNumber: 'QT-20241101-004',
            issueDate: new Date('2024-11-01').toISOString(),
            validUntilDate: new Date('2024-12-01').toISOString(),
            subtotal: 1805.0,
            tax: 324.9,
            total: 2129.9,
            notes: 'Üretim personeli için solunum fonksiyon testleri ve akciğer grafisi içeren paket.',
            status: 'sent',
            createdAt: new Date('2024-11-01').toISOString(),
            updatedAt: new Date('2024-11-01').toISOString(),
        },
        {
            companyId: 2,
            quoteNumber: 'QT-20241105-005',
            issueDate: new Date('2024-11-05').toISOString(),
            validUntilDate: new Date('2024-12-05').toISOString(),
            subtotal: 2750.0,
            tax: 495.0,
            total: 3245.0,
            notes: 'Yıllık periyodik muayene - Tam kan sayımı ve biyokimya paneli dahil kapsamlı tarama.',
            status: 'sent',
            createdAt: new Date('2024-11-05').toISOString(),
            updatedAt: new Date('2024-11-05').toISOString(),
        },
        {
            companyId: 3,
            quoteNumber: 'QT-20241108-006',
            issueDate: new Date('2024-11-08').toISOString(),
            validUntilDate: new Date('2024-12-08').toISOString(),
            subtotal: 1425.0,
            tax: 256.5,
            total: 1681.5,
            notes: 'Görsel yoğun işlerde çalışan personel için göz muayenesi ve fizik muayene paketi.',
            status: 'sent',
            createdAt: new Date('2024-11-08').toISOString(),
            updatedAt: new Date('2024-11-08').toISOString(),
        },
        {
            companyId: 1,
            quoteNumber: 'QT-20241112-007',
            issueDate: new Date('2024-11-12').toISOString(),
            validUntilDate: new Date('2024-12-12').toISOString(),
            subtotal: 3120.0,
            tax: 561.6,
            total: 3681.6,
            notes: 'İşe giriş öncesi kapsamlı sağlık taraması - Laboratuvar testleri ve görüntüleme dahil.',
            status: 'sent',
            createdAt: new Date('2024-11-12').toISOString(),
            updatedAt: new Date('2024-11-12').toISOString(),
        },
        {
            companyId: 2,
            quoteNumber: 'QT-20241115-008',
            issueDate: new Date('2024-11-15').toISOString(),
            validUntilDate: new Date('2024-12-15').toISOString(),
            subtotal: 2100.0,
            tax: 378.0,
            total: 2478.0,
            notes: 'Tehlikeli kimyasallarla çalışan personel için özel tarama paketi.',
            status: 'sent',
            createdAt: new Date('2024-11-15').toISOString(),
            updatedAt: new Date('2024-11-15').toISOString(),
        },
        {
            companyId: 3,
            quoteNumber: 'QT-20241120-009',
            issueDate: new Date('2024-11-20').toISOString(),
            validUntilDate: new Date('2024-12-20').toISOString(),
            subtotal: 1950.0,
            tax: 351.0,
            total: 2301.0,
            notes: 'Sürücü ve ağır araç operatörleri için sağlık muayenesi paketi.',
            status: 'accepted',
            createdAt: new Date('2024-11-20').toISOString(),
            updatedAt: new Date('2024-11-20').toISOString(),
        },
        {
            companyId: 1,
            quoteNumber: 'QT-20241122-010',
            issueDate: new Date('2024-11-22').toISOString(),
            validUntilDate: new Date('2024-12-22').toISOString(),
            subtotal: 2850.0,
            tax: 513.0,
            total: 3363.0,
            notes: 'Yüksekte çalışan personel için özel sağlık taraması - EKG ve SFT testleri dahil.',
            status: 'accepted',
            createdAt: new Date('2024-11-22').toISOString(),
            updatedAt: new Date('2024-11-22').toISOString(),
        },
        {
            companyId: 2,
            quoteNumber: 'QT-20241125-011',
            issueDate: new Date('2024-11-25').toISOString(),
            validUntilDate: new Date('2024-12-25').toISOString(),
            subtotal: 1680.0,
            tax: 302.4,
            total: 1982.4,
            notes: 'Gece vardiyasında çalışan personel için temel sağlık taraması.',
            status: 'accepted',
            createdAt: new Date('2024-11-25').toISOString(),
            updatedAt: new Date('2024-11-25').toISOString(),
        },
        {
            companyId: 3,
            quoteNumber: 'QT-20241128-012',
            issueDate: new Date('2024-11-28').toISOString(),
            validUntilDate: new Date('2024-12-28').toISOString(),
            subtotal: 3650.0,
            tax: 657.0,
            total: 4307.0,
            notes: 'İnşaat sahası personeli için kapsamlı sağlık muayenesi - Toz ve gürültü maruziyeti testleri.',
            status: 'accepted',
            createdAt: new Date('2024-11-28').toISOString(),
            updatedAt: new Date('2024-11-28').toISOString(),
        },
        {
            companyId: 1,
            quoteNumber: 'QT-20241201-013',
            issueDate: new Date('2024-12-01').toISOString(),
            validUntilDate: new Date('2024-12-31').toISOString(),
            subtotal: 1250.0,
            tax: 225.0,
            total: 1475.0,
            notes: 'Periyodik sağlık taraması - Sadece temel testler talep edilmiştir.',
            status: 'rejected',
            createdAt: new Date('2024-12-01').toISOString(),
            updatedAt: new Date('2024-12-01').toISOString(),
        },
        {
            companyId: 2,
            quoteNumber: 'QT-20241205-014',
            issueDate: new Date('2024-12-05').toISOString(),
            validUntilDate: new Date('2025-01-04').toISOString(),
            subtotal: 2450.0,
            tax: 441.0,
            total: 2891.0,
            notes: 'Özel izinli çalışanlar için gelişmiş tarama paketi. Fiyat yüksek bulundu.',
            status: 'rejected',
            createdAt: new Date('2024-12-05').toISOString(),
            updatedAt: new Date('2024-12-05').toISOString(),
        },
    ];

    // Insert quotes first
    await db.insert(quotes).values(sampleQuotes);
    console.log('✅ Quotes inserted successfully');

    // Sample quote items data
    const sampleQuoteItems = [
        // Quote 1 items (QT-20241015-001)
        {
            quoteId: 1,
            healthTestId: 1,
            quantity: 20,
            unitPrice: 200.0,
            totalPrice: 4000.0,
            description: 'Odyometri (İşitme Testi) - 20 çalışan',
            createdAt: new Date('2024-10-15').toISOString(),
            updatedAt: new Date('2024-10-15').toISOString(),
        },
        {
            quoteId: 1,
            healthTestId: 2,
            quantity: 20,
            unitPrice: 150.0,
            totalPrice: 3000.0,
            description: 'EKG (Elektrokardiyografi) - 20 çalışan',
            createdAt: new Date('2024-10-15').toISOString(),
            updatedAt: new Date('2024-10-15').toISOString(),
        },
        {
            quoteId: 1,
            healthTestId: 9,
            quantity: 20,
            unitPrice: 75.0,
            totalPrice: 1500.0,
            description: 'Fizik Muayene - 20 çalışan',
            createdAt: new Date('2024-10-15').toISOString(),
            updatedAt: new Date('2024-10-15').toISOString(),
        },

        // Quote 2 items (QT-20241020-002)
        {
            quoteId: 2,
            healthTestId: 5,
            quantity: 15,
            unitPrice: 120.0,
            totalPrice: 1800.0,
            description: 'Tam Kan Sayımı - 15 çalışan',
            createdAt: new Date('2024-10-20').toISOString(),
            updatedAt: new Date('2024-10-20').toISOString(),
        },
        {
            quoteId: 2,
            healthTestId: 7,
            quantity: 15,
            unitPrice: 80.0,
            totalPrice: 1200.0,
            description: 'İdrar Tahlili - 15 çalışan',
            createdAt: new Date('2024-10-20').toISOString(),
            updatedAt: new Date('2024-10-20').toISOString(),
        },
        {
            quoteId: 2,
            healthTestId: 9,
            quantity: 15,
            unitPrice: 75.0,
            totalPrice: 1125.0,
            description: 'Fizik Muayene - 15 çalışan',
            createdAt: new Date('2024-10-20').toISOString(),
            updatedAt: new Date('2024-10-20').toISOString(),
        },

        // Quote 3 items (QT-20241025-003)
        {
            quoteId: 3,
            healthTestId: 1,
            quantity: 25,
            unitPrice: 200.0,
            totalPrice: 5000.0,
            description: 'Odyometri (İşitme Testi) - Gürültülü ortam çalışanları - 25 kişi',
            createdAt: new Date('2024-10-25').toISOString(),
            updatedAt: new Date('2024-10-25').toISOString(),
        },
        {
            quoteId: 3,
            healthTestId: 4,
            quantity: 25,
            unitPrice: 300.0,
            totalPrice: 7500.0,
            description: 'SFT (Solunum Fonksiyon Testi) - 25 çalışan',
            createdAt: new Date('2024-10-25').toISOString(),
            updatedAt: new Date('2024-10-25').toISOString(),
        },
        {
            quoteId: 3,
            healthTestId: 9,
            quantity: 25,
            unitPrice: 75.0,
            totalPrice: 1875.0,
            description: 'Fizik Muayene - 25 çalışan',
            createdAt: new Date('2024-10-25').toISOString(),
            updatedAt: new Date('2024-10-25').toISOString(),
        },

        // Quote 4 items (QT-20241101-004)
        {
            quoteId: 4,
            healthTestId: 4,
            quantity: 12,
            unitPrice: 300.0,
            totalPrice: 3600.0,
            description: 'SFT (Solunum Fonksiyon Testi) - Üretim personeli - 12 kişi',
            createdAt: new Date('2024-11-01').toISOString(),
            updatedAt: new Date('2024-11-01').toISOString(),
        },
        {
            quoteId: 4,
            healthTestId: 3,
            quantity: 12,
            unitPrice: 250.0,
            totalPrice: 3000.0,
            description: 'Akciğer Grafisi - 12 çalışan',
            createdAt: new Date('2024-11-01').toISOString(),
            updatedAt: new Date('2024-11-01').toISOString(),
        },

        // Quote 5 items (QT-20241105-005)
        {
            quoteId: 5,
            healthTestId: 5,
            quantity: 18,
            unitPrice: 120.0,
            totalPrice: 2160.0,
            description: 'Tam Kan Sayımı - 18 çalışan',
            createdAt: new Date('2024-11-05').toISOString(),
            updatedAt: new Date('2024-11-05').toISOString(),
        },
        {
            quoteId: 5,
            healthTestId: 6,
            quantity: 18,
            unitPrice: 180.0,
            totalPrice: 3240.0,
            description: 'Biyokimya Paneli - 18 çalışan',
            createdAt: new Date('2024-11-05').toISOString(),
            updatedAt: new Date('2024-11-05').toISOString(),
        },
        {
            quoteId: 5,
            healthTestId: 7,
            quantity: 18,
            unitPrice: 80.0,
            totalPrice: 1440.0,
            description: 'İdrar Tahlili - 18 çalışan',
            createdAt: new Date('2024-11-05').toISOString(),
            updatedAt: new Date('2024-11-05').toISOString(),
        },
        {
            quoteId: 5,
            healthTestId: 9,
            quantity: 18,
            unitPrice: 75.0,
            totalPrice: 1350.0,
            description: 'Fizik Muayene - 18 çalışan',
            createdAt: new Date('2024-11-05').toISOString(),
            updatedAt: new Date('2024-11-05').toISOString(),
        },

        // Quote 6 items (QT-20241108-006)
        {
            quoteId: 6,
            healthTestId: 8,
            quantity: 10,
            unitPrice: 100.0,
            totalPrice: 1000.0,
            description: 'Göz Muayenesi - Görsel yoğun iş - 10 çalışan',
            createdAt: new Date('2024-11-08').toISOString(),
            updatedAt: new Date('2024-11-08').toISOString(),
        },
        {
            quoteId: 6,
            healthTestId: 9,
            quantity: 10,
            unitPrice: 75.0,
            totalPrice: 750.0,
            description: 'Fizik Muayene - 10 çalışan',
            createdAt: new Date('2024-11-08').toISOString(),
            updatedAt: new Date('2024-11-08').toISOString(),
        },
        {
            quoteId: 6,
            healthTestId: 5,
            quantity: 10,
            unitPrice: 120.0,
            totalPrice: 1200.0,
            description: 'Tam Kan Sayımı - 10 çalışan',
            createdAt: new Date('2024-11-08').toISOString(),
            updatedAt: new Date('2024-11-08').toISOString(),
        },

        // Quote 7 items (QT-20241112-007)
        {
            quoteId: 7,
            healthTestId: 2,
            quantity: 15,
            unitPrice: 150.0,
            totalPrice: 2250.0,
            description: 'EKG (Elektrokardiyografi) - İşe giriş - 15 çalışan',
            createdAt: new Date('2024-11-12').toISOString(),
            updatedAt: new Date('2024-11-12').toISOString(),
        },
        {
            quoteId: 7,
            healthTestId: 3,
            quantity: 15,
            unitPrice: 250.0,
            totalPrice: 3750.0,
            description: 'Akciğer Grafisi - 15 çalışan',
            createdAt: new Date('2024-11-12').toISOString(),
            updatedAt: new Date('2024-11-12').toISOString(),
        },
        {
            quoteId: 7,
            healthTestId: 5,
            quantity: 15,
            unitPrice: 120.0,
            totalPrice: 1800.0,
            description: 'Tam Kan Sayımı - 15 çalışan',
            createdAt: new Date('2024-11-12').toISOString(),
            updatedAt: new Date('2024-11-12').toISOString(),
        },
        {
            quoteId: 7,
            healthTestId: 6,
            quantity: 15,
            unitPrice: 180.0,
            totalPrice: 2700.0,
            description: 'Biyokimya Paneli - 15 çalışan',
            createdAt: new Date('2024-11-12').toISOString(),
            updatedAt: new Date('2024-11-12').toISOString(),
        },
        {
            quoteId: 7,
            healthTestId: 9,
            quantity: 15,
            unitPrice: 75.0,
            totalPrice: 1125.0,
            description: 'Fizik Muayene - 15 çalışan',
            createdAt: new Date('2024-11-12').toISOString(),
            updatedAt: new Date('2024-11-12').toISOString(),
        },

        // Quote 8 items (QT-20241115-008)
        {
            quoteId: 8,
            healthTestId: 6,
            quantity: 12,
            unitPrice: 180.0,
            totalPrice: 2160.0,
            description: 'Biyokimya Paneli - Kimyasal maruziyet - 12 çalışan',
            createdAt: new Date('2024-11-15').toISOString(),
            updatedAt: new Date('2024-11-15').toISOString(),
        },
        {
            quoteId: 8,
            healthTestId: 4,
            quantity: 12,
            unitPrice: 300.0,
            totalPrice: 3600.0,
            description: 'SFT (Solunum Fonksiyon Testi) - 12 çalışan',
            createdAt: new Date('2024-11-15').toISOString(),
            updatedAt: new Date('2024-11-15').toISOString(),
        },
        {
            quoteId: 8,
            healthTestId: 9,
            quantity: 12,
            unitPrice: 75.0,
            totalPrice: 900.0,
            description: 'Fizik Muayene - 12 çalışan',
            createdAt: new Date('2024-11-15').toISOString(),
            updatedAt: new Date('2024-11-15').toISOString(),
        },

        // Quote 9 items (QT-20241120-009)
        {
            quoteId: 9,
            healthTestId: 2,
            quantity: 8,
            unitPrice: 150.0,
            totalPrice: 1200.0,
            description: 'EKG (Elektrokardiyografi) - Sürücü personel - 8 kişi',
            createdAt: new Date('2024-11-20').toISOString(),
            updatedAt: new Date('2024-11-20').toISOString(),
        },
        {
            quoteId: 9,
            healthTestId: 8,
            quantity: 8,
            unitPrice: 100.0,
            totalPrice: 800.0,
            description: 'Göz Muayenesi - 8 çalışan',
            createdAt: new Date('2024-11-20').toISOString(),
            updatedAt: new Date('2024-11-20').toISOString(),
        },
        {
            quoteId: 9,
            healthTestId: 9,
            quantity: 8,
            unitPrice: 75.0,
            totalPrice: 600.0,
            description: 'Fizik Muayene - 8 çalışan',
            createdAt: new Date('2024-11-20').toISOString(),
            updatedAt: new Date('2024-11-20').toISOString(),
        },
        {
            quoteId: 9,
            healthTestId: 5,
            quantity: 8,
            unitPrice: 120.0,
            totalPrice: 960.0,
            description: 'Tam Kan Sayımı - 8 çalışan',
            createdAt: new Date('2024-11-20').toISOString(),
            updatedAt: new Date('2024-11-20').toISOString(),
        },

        // Quote 10 items (QT-20241122-010)
        {
            quoteId: 10,
            healthTestId: 2,
            quantity: 10,
            unitPrice: 150.0,
            totalPrice: 1500.0,
            description: 'EKG (Elektrokardiyografi) - Yüksekte çalışma - 10 kişi',
            createdAt: new Date('2024-11-22').toISOString(),
            updatedAt: new Date('2024-11-22').toISOString(),
        },
        {
            quoteId: 10,
            healthTestId: 4,
            quantity: 10,
            unitPrice: 300.0,
            totalPrice: 3000.0,
            description: 'SFT (Solunum Fonksiyon Testi) - 10 çalışan',
            createdAt: new Date('2024-11-22').toISOString(),
            updatedAt: new Date('2024-11-22').toISOString(),
        },
        {
            quoteId: 10,
            healthTestId: 8,
            quantity: 10,
            unitPrice: 100.0,
            totalPrice: 1000.0,
            description: 'Göz Muayenesi - 10 çalışan',
            createdAt: new Date('2024-11-22').toISOString(),
            updatedAt: new Date('2024-11-22').toISOString(),
        },
        {
            quoteId: 10,
            healthTestId: 9,
            quantity: 10,
            unitPrice: 75.0,
            totalPrice: 750.0,
            description: 'Fizik Muayene - 10 çalışan',
            createdAt: new Date('2024-11-22').toISOString(),
            updatedAt: new Date('2024-11-22').toISOString(),
        },

        // Quote 11 items (QT-20241125-011)
        {
            quoteId: 11,
            healthTestId: 5,
            quantity: 14,
            unitPrice: 120.0,
            totalPrice: 1680.0,
            description: 'Tam Kan Sayımı - Gece vardiyası - 14 çalışan',
            createdAt: new Date('2024-11-25').toISOString(),
            updatedAt: new Date('2024-11-25').toISOString(),
        },
        {
            quoteId: 11,
            healthTestId: 7,
            quantity: 14,
            unitPrice: 80.0,
            totalPrice: 1120.0,
            description: 'İdrar Tahlili - 14 çalışan',
            createdAt: new Date('2024-11-25').toISOString(),
            updatedAt: new Date('2024-11-25').toISOString(),
        },
        {
            quoteId: 11,
            healthTestId: 9,
            quantity: 14,
            unitPrice: 75.0,
            totalPrice: 1050.0,
            description: 'Fizik Muayene - 14 çalışan',
            createdAt: new Date('2024-11-25').toISOString(),
            updatedAt: new Date('2024-11-25').toISOString(),
        },

        // Quote 12 items (QT-20241128-012)
        {
            quoteId: 12,
            healthTestId: 1,
            quantity: 22,
            unitPrice: 200.0,
            totalPrice: 4400.0,
            description: 'Odyometri (İşitme Testi) - İnşaat sahası - 22 çalışan',
            createdAt: new Date('2024-11-28').toISOString(),
            updatedAt: new Date('2024-11-28').toISOString(),
        },
        {
            quoteId: 12,
            healthTestId: 4,
            quantity: 22,
            unitPrice: 300.0,
            totalPrice: 6600.0,
            description: 'SFT (Solunum Fonksiyon Testi) - Toz maruziyeti - 22 çalışan',
            createdAt: new Date('2024-11-28').toISOString(),
            updatedAt: new Date('2024-11-28').toISOString(),
        },
        {
            quoteId: 12,
            healthTestId: 3,
            quantity: 22,
            unitPrice: 250.0,
            totalPrice: 5500.0,
            description: 'Akciğer Grafisi - 22 çalışan',
            createdAt: new Date('2024-11-28').toISOString(),
            updatedAt: new Date('2024-11-28').toISOString(),
        },
        {
            quoteId: 12,
            healthTestId: 9,
            quantity: 22,
            unitPrice: 75.0,
            totalPrice: 1650.0,
            description: 'Fizik Muayene - 22 çalışan',
            createdAt: new Date('2024-11-28').toISOString(),
            updatedAt: new Date('2024-11-28').toISOString(),
        },

        // Quote 13 items (QT-20241201-013)
        {
            quoteId: 13,
            healthTestId: 5,
            quantity: 8,
            unitPrice: 120.0,
            totalPrice: 960.0,
            description: 'Tam Kan Sayımı - 8 çalışan',
            createdAt: new Date('2024-12-01').toISOString(),
            updatedAt: new Date('2024-12-01').toISOString(),
        },
        {
            quoteId: 13,
            healthTestId: 9,
            quantity: 8,
            unitPrice: 75.0,
            totalPrice: 600.0,
            description: 'Fizik Muayene - 8 çalışan',
            createdAt: new Date('2024-12-01').toISOString(),
            updatedAt: new Date('2024-12-01').toISOString(),
        },

        // Quote 14 items (QT-20241205-014)
        {
            quoteId: 14,
            healthTestId: 2,
            quantity: 10,
            unitPrice: 150.0,
            totalPrice: 1500.0,
            description: 'EKG (Elektrokardiyografi) - 10 çalışan',
            createdAt: new Date('2024-12-05').toISOString(),
            updatedAt: new Date('2024-12-05').toISOString(),
        },
        {
            quoteId: 14,
            healthTestId: 3,
            quantity: 10,
            unitPrice: 250.0,
            totalPrice: 2500.0,
            description: 'Akciğer Grafisi - 10 çalışan',
            createdAt: new Date('2024-12-05').toISOString(),
            updatedAt: new Date('2024-12-05').toISOString(),
        },
        {
            quoteId: 14,
            healthTestId: 6,
            quantity: 10,
            unitPrice: 180.0,
            totalPrice: 1800.0,
            description: 'Biyokimya Paneli - 10 çalışan',
            createdAt: new Date('2024-12-05').toISOString(),
            updatedAt: new Date('2024-12-05').toISOString(),
        },
    ];

    // Insert quote items
    await db.insert(quoteItems).values(sampleQuoteItems);
    console.log('✅ Quote items inserted successfully');
    
    console.log('✅ Quotes comprehensive seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});